print("BAMN Movement!")
print("By Any Means Neccesary")
print("BAMN Movement!")
print("By Any Means Neccesary")
print("BAMN Movement!")
print("By Any Means Neccesary")
print("BAMN Movement!")
print("By Any Means Neccesary")
print("BAMN Movement!")
print("By Any Means Neccesary")
print("BAMN Movement!")
print("By Any Means Neccesary")
print("BAMN Movement!")
print("By Any Means Neccesary")
print("BAMN Movement!")
print("By Any Means Neccesary")
print("BAMN Movement!")
print("By Any Means Neccesary")
print("BAMN Movement!")
print("By Any Means Neccesary")
print("BAMN Movement!")
print("By Any Means Neccesary")
print("BAMN Movement!")
print("By Any Means Neccesary")
print("BAMN Movement!")
print("By Any Means Neccesary")
print("BAMN Movement!")
print("By Any Means Neccesary")
print("BAMN Movement!")
print("By Any Means Neccesary")
